application: bccblog2
version: live
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /.*
  script: static.py

libraries:
- name: django
  version: "1.2"
- name: ssl 
  version: latest


env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
